apiVersion: v1
kind: Secret
metadata:
  name: toss-secrets
  namespace: toss-system
type: Opaque
data:
  # Base64 encoded secrets
  SPRING_DATASOURCE_PASSWORD: dG9zc19wYXNzd29yZA==  # toss_password
  JWT_SECRET: bXlTZWNyZXRLZXkxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=  # mySecretKey123456789012345678901234567890
